export const EMAIL_VERIFICATION_GRACE_PERIOD_HOURS = 48;
export const EMAIL_VERIFICATION_GRACE_PERIOD_MS =
  EMAIL_VERIFICATION_GRACE_PERIOD_HOURS * 60 * 60 * 1000;
export const EMAIL_VERIFICATION_GRACE_PERIOD_DAYS =
  EMAIL_VERIFICATION_GRACE_PERIOD_HOURS / 24;
